USE STOREFRONT;


SELECT 
    ORDER_ID, ORDER_DATE, AMOUNT
FROM
    ORDERS
ORDER BY ORDER_ID DESC
LIMIT 50;


SELECT 
    ORDER_ID, ORDER_DATE, AMOUNT
FROM
    ORDERS
ORDER BY AMOUNT DESC
LIMIT 10;


SELECT 
    ORDER_ID, ORDER_DATE, AMOUNT
FROM
    ORDERS
WHERE
    DATEDIFF(CURDATE(), ORDER_DATE) >= 10 AND order_status = 'Not Shipped';


SELECT 
    SHOPPER.SHOPPER_NAME
FROM
    SHOPPER,
    ORDERS
WHERE
    SHOPPER.SHOPPER_ID = ORDERS.SHOPPER_ID AND DATEDIFF(CURDATE(), ORDER_DATE) >= 30;


SELECT 
    SHOPPER.SHOPPER_NAME,
    ORDERS.order_id,
    ORDERS.AMOUNT,
    ORDERS.ORDER_STATUS
FROM
    SHOPPER,
    ORDERS
WHERE
    SHOPPER.SHOPPER_ID = ORDERS.SHOPPER_ID AND DATEDIFF(CURDATE(), ORDER_DATE) <= 15;
 
 
SELECT 
    PRODUCT_NAME
FROM
    ITEMS_ORDERED
        INNER JOIN
    ORDERS ON ORDERS.ORDER_ID = ITEMS_ORDERED.ORDER_ID
WHERE
    ORDERS.ORDER_ID = 1 AND ORDERS.ORDER_STATUS = 'Shipped'; 
  

SELECT 
    ITEMS_ORDERED.PRODUCT_NAME, ORDERS.ORDER_DATE
FROM
    ITEMS_ORDERED
        INNER JOIN
    ORDERS ON ORDERS.ORDER_ID = ITEMS_ORDERED.ORDER_ID
WHERE
    ORDERS.AMOUNT BETWEEN 20000 AND 50000;