USE StoreFront;

SELECT 
    PRODUCT.PRODUCT_ID,
    PRODUCT.NAME AS PRODUCT_TITLE,
    CATEGORY.NAME AS CATEGORY_TITLE,
    PRODUCT.PRICE
FROM
    PRODUCT,
    CATEGORY
WHERE
    PRODUCT.CATEGORY_ID = CATEGORY.CATEGORY_ID
ORDER BY PRODUCT.PRODUCT_ID DESC ;


SELECT 
    NAME AS PRODUCT_TITLE
FROM
    PRODUCT
WHERE
    IMAGE IS NULL;


SELECT 
    Category1.CATEGORY_ID AS ID,
    Category1.NAME AS CATEGORY_TITLE,
    IFNULL(Category2.NAME, 'Top Category') AS PARENT_CATEGORY
FROM
    CATEGORY Category1
        LEFT JOIN
    CATEGORY Category2 ON Category1.PARENT_CATEGORY = Category2.CATEGORY_ID
ORDER BY Category2.name, Category1.NAME;



SELECT 
    Category1.CATEGORY_ID AS ID,
    Category1.NAME AS CATEGORY_TITLE,
    Category2.NAME AS PARENT_CATEGORY
FROM
    CATEGORY Category1
        LEFT JOIN
    CATEGORY Category2 ON Category1.PARENT_CATEGORY = Category2.CATEGORY_ID
WHERE
    Category1.CATEGORY_ID NOT IN (SELECT 
        PARENT_CATEGORY
    FROM
        CATEGORY
    WHERE
        PARENT_CATEGORY IS NOT NULL);
        
        

SELECT 
    product.PRODUCT_ID AS ID, product.PRICE, product.NAME AS PRODUCT_TITLE, Category.name AS CATEGORY_NAME
FROM
    PRODUCT product
        LEFT JOIN
    CATEGORY Category ON Category.CATEGORY_ID = product.CATEGORY_ID
WHERE
    Category.NAME IN ('MOBILE') ;
    
    

SELECT 
    NAME
FROM
    PRODUCT
WHERE
    QUANTITY <= 50;